### ISSUE TITLE
Support a debug format that will send the textformat-version instead?

### ISSUE THREAD

**Issue by robpaveza** [dropwizard/dropwizard-protobuf#12]
Would you be supportive of using a querystring parameter or some other form of query that would allow developers to receive the response in text format instead of the message in binary?  E.g.:

/someendpoint/?debug-prototextfmt=true

results in calling `m.toString()` instead of `m.toByteArray()`

**Comment by jplock** [comment]
This bundle doesn't do a whole lot beyond providing the Jersey encoder/decoder, I'm not sure how we'd implement this.

**Comment by robpaveza** [comment]
I had to modify my endpoint to also specify `@Produces("application/x-protobuf,application/x-protobuf-text-format")`, but once I sent the `Accept: application/x-protobuf-text-format` header in my request, it lit up automatically.

**Comment by jplock** [comment]
Closed by #14
