### ISSUE TITLE
Give option to print default values in JSON bodies

### ISSUE THREAD

**Issue by mdowell12** [dropwizard/dropwizard-protobuf#168]
In the current `ProtocolBufferMessageBodyProvider` implementation, default values in a Protobuf message are not printed in the JSON body. This is because `JsonFormat.printer()`, by default, does not print default values. So if you have a Protobuf message like:
```
message MyMessage {
    enum Outcome {
        DENY = 0;
        ALLOW = 1;
    }

    Outcome my_outcome = 0;

}
```
and your Protobuf message has the value `my_outcome == Outcome.DENY`, then `my_outcome` will not be included in the JSON body.

I've been able to change this by using the `includingDefaultValueFields` option to format the Protobuf messages in `ProtocolBufferMessageBodyProvider`:
```
final String formatted = JsonFormat.printer().omittingInsignificantWhitespace().includingDefaultValueFields().print(m);
```
Using this code, `formatted` _would_ include `my_outcome` in the example above.

This is a nice feature, especially when the JSON is consumed by folks without knowledge of Protobuf or the models my service uses.

What do you think about making it an option for this library? If you agree it'd be useful, I'd be happy to contribute.

**Comment by jplock** [comment]
Sounds good, can you please submit a PR
