### ISSUE TITLE
Superfluous copy of response

### ISSUE THREAD

**Issue by Till--H** [dropwizard/dropwizard-protobuf#18]
Hi,

I noticed that the reponse proto is superfluously copied before writing it to the output stream:

https://github.com/dropwizard/dropwizard-protobuf/blob/master/src/main/java/io/dropwizard/jersey/protobuf/ProtocolBufferMessageBodyProvider.java#L95

Seems like a 
```
m.writeTo(entityStream);
```
should do the same, but save the additional in-memory copy of the response, or am I overlooking something?

**Comment by jplock** [comment]
I wasn't aware of `writeTo`, that sounds like it might work, I'll look into it.  Thanks!
