### ISSUE TITLE
InvalidProtocolBufferExceptions thrown in ProtocolBufferMessageBodyProvider are not caught by InvalidProtocolBufferExceptionMapper

### ISSUE THREAD

**Issue by Mistodon** [dropwizard/dropwizard-protobuf#23]
While `ProtocolBufferMessageBodyProvider` [claims to throw IOExceptions](https://github.com/dropwizard/dropwizard-protobuf/blob/master/src/main/java/io/dropwizard/jersey/protobuf/ProtocolBufferMessageBodyProvider.java#L74) - it actually catches any exception and unconditionally [throws a WebApplicationException](https://github.com/dropwizard/dropwizard-protobuf/blob/master/src/main/java/io/dropwizard/jersey/protobuf/ProtocolBufferMessageBodyProvider.java#L96).

This means if an endpoint accepts a protobuf message, but is sent invalid data by a client, instead of returning a 400, as the `InvalidProtocolBufferExceptionMapper` would do if it caught an `InvalidProtocolBufferException` - a 500 error is returned.

It seems to me the the message body provider should catch and rethrow IOExceptions, or at least InvalidProtocolBufferExceptions.

If this is the intended behaviour, I can open a PR for it.

**Comment by Galbar** [comment]
I just had the same issue. I would be very interested in knowing if it is a bug, and have it fixed; or if it is intended behavior.
