### ISSUE TITLE
Need the new build for 2.0.x-y as there are cve's from protobuf

### ISSUE THREAD

**Issue by bharatgoelharness** [dropwizard/dropwizard-protobuf#574]
@joschi When is the new release planned?

**Comment by joschi** [comment]
Enjoy: https://github.com/dropwizard/dropwizard-protobuf/releases/tag/v2.1.11

And while you're at it, upgrade to Dropwizard 3.x or 4.x.

Dropwizard 2.1.x was EOL beginning of this year, and Dropwizard 2.0.x long, long before that:
- https://github.com/dropwizard/dropwizard/discussions/6324
- https://github.com/dropwizard/dropwizard/discussions/7880

**Comment by bharatgoelharness** [comment]
@joschi Thnak you quickly releasing this. Appreciate your help.
when this will be available as a maven artifact
